# pyproject.toml
[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[project.scripts]
sherlock_lit = "sherlock_lit.cli:main"

[project]
name = "Sherlock-lit"
version = "0.1.1"
authors = [
  { name="anvix9", email="epononanvi@gmail.com" },
]
description = "First version of sherlock for NLP papers."
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/anvix9/sherlock-lit"
Issues = "https://github.com/anvix9/sherlock-lit/issues"
