name: sherlock-lit
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}
    - name: Pull Docker Image from ECR
      run: |
        docker pull ${{ secrets.ECR_REPOSITORY_URI }}:latest
    - name: Install Dependencies
      run: |
        docker run --rm -v $(pwd):/app ${{ secrets.ECR_REPOSITORY_URI }}:latest bash -c 'pip install arxiv'
    - name: Logout from Docker
      run: |
        docker logout ${{ secrets.ECR_REPOSITORY_URI }}
